<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
    <UserSecretsId>bde44560-6d21-40eb-bd09-82c35fa5c7cf</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NonFactors.Grid.Mvc6" Version="8.0.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
    <PackageReference
      Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"
      Version="10.0.1"
    />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="SuumoScraping.Domain\SuumoScraping.Domain.csproj" />
    <ProjectReference Include="SuumoScraping.Application\SuumoScraping.Application.csproj" />
    <ProjectReference Include="SuumoScraping.Infrastructure\SuumoScraping.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Views\Bukken\" />
    <Folder Include="Views\File\" />
    <Folder Include="wwwroot\lib\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="SuumoScraping.Tests\**" />
    <Content Remove="SuumoScraping.Tests\**" />
    <EmbeddedResource Remove="SuumoScraping.Tests\**" />
    <None Remove="SuumoScraping.Tests\**" />
    <Compile Remove="SuumoScraping.Domain\**" />
    <Compile Remove="SuumoScraping.Application\**" />
    <Compile Remove="SuumoScraping.Infrastructure\**" />
    <Content Remove="SuumoScraping.Domain\**" />
    <Content Remove="SuumoScraping.Application\**" />
    <Content Remove="SuumoScraping.Infrastructure\**" />
    <EmbeddedResource Remove="SuumoScraping.Domain\**" />
    <EmbeddedResource Remove="SuumoScraping.Application\**" />
    <EmbeddedResource Remove="SuumoScraping.Infrastructure\**" />
    <None Remove="SuumoScraping.Domain\**" />
    <None Remove="SuumoScraping.Application\**" />
    <None Remove="SuumoScraping.Infrastructure\**" />
  </ItemGroup>
</Project>
