// <auto-generated />
namespace WebApplication3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBukenNewAccess2Property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBukenNewAccess2Property));
        
        string IMigrationMetadata.Id
        {
            get { return "201606271117222_AddBukenNewAccess2Property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
